Add missing c++11 to makefile
I get a lot of compilation errors like
```
In file included from parser/mpError.cpp:36:
In file included from parser/mpIToken.h:40:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:1351:5: error: too many
      template arguments for class template 'auto_ptr'
    unique_ptr<__node, _Dp> __hold(__node_alloc_traits::allocate(__na, 1), _Dp(__na, 1));
    ^                  ~~~~
parser/mpCompat.h:50:22: note: expanded from macro 'unique_ptr'
  #define unique_ptr auto_ptr
                     ^
```
without -std=c++11 in makefile.